apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - storage.yaml
  - pvcs.yaml
  - protonvpn-wg-sealed.yaml
  - slskd-sealed.yaml
  - network-policy.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
