apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: protonvpn-wg-conf
  namespace: slskd
spec:
  encryptedData:
    wg0.conf: AgCUDW0I6FO3LCmypkf405bapb5FydCmW30v24plSVoBe++TLGkgmEN38fXe0lDD4nn5dCDkokD88wnT9AgUZTmsYfCR1uuB9a4m/PS7V0p9I1wuNHJ9JB6mHFiOMpjjDnnMgn2/R6f7Qnyk1r/yPlbOiWQypLI5xfGbaDvnFRlNj53eTpRrFxVdarSZn+OBUK3uoN899CfLtvAzqdIzeaFrn3TwhG6TbJ5POxi0W19P0k1bria9cKl9gKafw6FHGFZucobFp9mzxbum/lUnjq5DF1n77rM3zf3u0seGoougqxGiFY9nh09yvBvdrbDlMNWMm7+qHC/Zsf9zRkhJlJP93LSOuQdHyOkWmoxYesseSh6KWBz4JjVVQNY7oDUWjyYIwKtSquqYzHnZLS1Zyy1LwC/fc50uwO+nuT29SdMOkE/7uhAlVriRn2pBWJEmZ0CD8Qgs4kFpcttPM+u1rl48+2wEK8hUgBrAd2/ARFZHWJOpkzr3iIw/LN3XMXC3cw10hblCgTCafMO6idE/9WrTD15Kt4jToZzrA3q50b4QvGnNhb8uGBgKbtzQ99UTvmCEGhmus7vHLHBCnS7ysrUWP9HSi2yPViClpB9652b4OnkWN4SvjinoiNyGnUS4RDvP+iAj5tDZMSXNu+rIsS4/tHlp6oxyc2ivgr4Q18KTya5804oNaSTDlp9R8glmjQJyvNCDlTWpZ+9aaZHBteIm/5HIE+ts8Pfwne93wdwResWIvdoYYv3kN94Ox8NIMUAY412xWlurysjkuw+M77yRUqx47saffzCeO2F55S9HSwuOrF0v8vGKr4nNpy+XxJbWez7GYTz/8HSYxdBhn/dqAzv0GOPVOdS+xcakE1LCNBHfjHhPlN4jNu037bHA+nytGUN3oMPM/ev19Q1blrGDDPJ07R+hxrfGYI5++PEvyrAc48GJQ6BOfEeuJ/ddrNv/OptXFH5/o3y87FRVBysdfLoiBkVLMSXtfOLzGXJRTUxWzMhMlQ2NP0Hnu04NUeYIT+TtMUv/QEpg2wwbdy0F/kIlXb6RRqPf/6zYxz0NL0RWB8A2lZgENx7jwUIRNrf9Z8RUNY7eeihZACBEs/JkIJpE+O1RoxRENI7vRysWSOgBYMGEHWFNU2K2ZdFXsSujkv0b5hIvk6GxE3m6j9AxNMuDLS5/YfHfwi4VhwU9q80Wsp/nhJXqAyWdRZzTx/Rb5yqV8YzWxJFU3uAzJtQgxSVbpCLrY2W2z1CmkOdO2ZKvhnFGX2qboBn95DMQ7CCa4neltETN11WRsSTcU2ckEN0aUOqSM1QCIWjTUEWhwWBz5A5USbt2sB5AXBhm4AZ/WqDQYwqWoOOxbA==
  template:
    metadata:
      creationTimestamp: null
      name: protonvpn-wg-conf
      namespace: slskd
    type: Opaque
