---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: democratic-csi-creds
  namespace: democratic-csi
spec:
  encryptedData:
    password: AgAX7nKAcBxMRHgVVH3JyPvB6DrYiF8usIn7ES3hVKN56xnyrwyjeBGaKkN29EQhtegoL8t/bRYhB/Lj2Wcidb/gNwExHQuqa/4pqVM1gaaASM/BxuOC5jZFtH39fr7wXni323cl7aMZnllYL4ll3dKdpvbUnK9XYw9aX/yy+zbA4PZr0wYWDtWZzCydv1bcnl9dtJXDlEaS+x1EaPN0UL5uShOni5sCo5yoth0ZUeXZBqzO/4yr8hAyfGXdt6Fn07CMZLhSaFkf4sxX4o87N0Yf6kiHpvvaFeBTS0c4BCK80Ao8jpcWQWoNXO2e6ehOwSE51bbnKx2LI6v8BVZIxw3gdoT8uLTscPJFkMwnBEzMWIMIG8ds4SmRmxugZQ/md4kZOmF8MTr3u6ISgzb10At7ZW8fKu30n8pFRM+/r1PaUD49TH02aAEX49KhkQ5LRQlBQSIZ/c8YhzZ9pEmPTQBb6IRgFj0OZ7k+i8zfptqbLdAkAY+azXfbNh/D1nYlyg49o2R6GyLNO2CUWjW9saiUrYrjrx5FAB/KF6lXimMLsQYS6LjVCMC7QXJ8/z/dbPX8Mgs5N9/wLC6CFatTVWl07mq7J/JF14jXJqCmiIwYi7w8SYKTNXdtfIlk13SXhKoqVOm7IxxSsTjvRNob97w1D78nwdvkKp8rNNSMjHyZ+OyKaVdqpLpevOjLBlUA2Dl+JL+gy2ZnkznoKNGByF/kzDsUVFOtatUF
  template:
    metadata:
      creationTimestamp: null
      name: democratic-csi-creds
      namespace: democratic-csi
    type: Opaque
