controller:
  enabled: true

node:
  enabled: true

csiDriver:
  name: org.democratic-csi.iscsi

storageClasses:
  - name: truenas-iscsi
    defaultClass: false
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: ext4

driver:
  config:
    driver: freenas-iscsi
    httpConnection:
      protocol: http
      host: truenas.local.gwg313.xyz
      port: 80
      username: csi
      password: ${TRUENAS_PASSWORD}
    zfs:
      datasetParentName: tank/k8s
      detachedSnapshots: false
      zvolCompression: lz4
    iscsi:
      targetPortal: truenas.local.gwg313.xyz
      targetPortals: []
      targetInterface: ""
      namePrefix: csi-
      nameSuffix: ""
      targetGroups:
        - targetGroupPortalGroup: 1
          targetGroupInitiatorGroup: 1
          targetGroupAuthType: CHAP
          targetGroupAuthGroup: 1
