apiVersion: v1
kind: PersistentVolume
metadata:
  name: focalboard-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    targetPortal: truenas.local.gwg313.xyz:3260
    iqn: iqn.2005-10.org.freenas.ctl:focalboard
    lun: 0
    fsType: ext4
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
      name: focalboard-iscsi-auth
  claimRef:
    namespace: focalboard
    name: focalboard-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: focalboard-data
  namespace: focalboard
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: focalboard-pv
