apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hedgedoc-uploads-pvc
  namespace: hedgedoc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: hedgedoc-uploads-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hedgedoc-db-pvc
  namespace: hedgedoc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: hedgedoc-db-pv
