---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hedgedoc-uploads-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    targetPortal: truenas.local.gwg313.xyz:3260
    iqn: iqn.2005-10.org.freenas.ctl:hedgedoc-data
    lun: 0
    fsType: ext4
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
      name: hedgedoc-iscsi-auth
  claimRef:
    namespace: hedgedoc
    name: hedgedoc-uploads-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hedgedoc-db-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    targetPortal: truenas.local.gwg313.xyz:3260
    iqn: iqn.2005-10.org.freenas.ctl:hedgedoc-database
    lun: 1
    fsType: ext4
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
      name: hedgedoc-iscsi-auth
  claimRef:
    namespace: hedgedoc
    name: hedgedoc-db-pvc
