apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: default-deployment-revision-history
spec:
  rules:
    - name: set-revision-history-limit
      match:
        any:
          - resources:
              kinds:
                - Deployment

      mutate:
        patchStrategicMerge:
          spec:
            +(revisionHistoryLimit): 3
