apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: default-container-resources
spec:
  background: true

  rules:
    - name: default-container-resources
      match:
        any:
          - resources:
              kinds:
                - Pod

      mutate:
        foreach:
          - list: "request.object.spec.containers"
            patchStrategicMerge:
              spec:
                containers:
                  - (name): "{{ element.name }}"
                    resources:
                      requests:
                        +(cpu): "100m"
                        +(memory): "128Mi"
                      limits:
                        +(cpu): "200m"
                        +(memory): "512Mi"

          - list: "request.object.spec.initContainers || []"
            patchStrategicMerge:
              spec:
                initContainers:
                  - (name): "{{ element.name }}"
                    resources:
                      requests:
                        +(cpu): "100m"
                        +(memory): "128Mi"
                      limits:
                        +(cpu): "200m"
                        +(memory): "512Mi"
