apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - default-container-resources.yaml
  - default-cronjob-history.yaml
  - default-deployment-revision-history.yaml
  - default-drop-all-capabilities.yaml
  - default-job-ttl.yaml
  - default-run-as-non-root.yaml
  - default-seccomp-runtime-default.yaml

commonLabels:
  app.kubernetes.io/part-of: kyverno-policies
  policy-tier: defaults

commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"
