apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bytestash
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: bytestash
  source:
    repoURL: https://github.com/gwg313/homelab-gitops.git
    path: apps/bytestash
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
