apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-gitops-ci
  namespace: argocd
  annotations:
    argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/gwg313/homelab-gitops.git
    targetRevision: main
    path: apps/homelab-gitops
  destination:
    server: https://kubernetes.default.svc
    namespace: cicd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
