apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kyverno-core.yaml
  - kyverno-policies.yaml
  - tetragon-core.yaml
  - tetragon-policies.yaml
  - sealed-secrets.yaml
  - cert-manager.yaml
  - forgejo.yaml
  - navidrome.yaml
