apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kyverno-core.yaml
  - kyverno-policies.yaml
  - tetragon-core.yaml
  - tetragon-policies.yaml
  - sealed-secrets.yaml
  - cert-manager.yaml
  - monitoring.yaml
  - nfs-subdir.yaml
  - harbor.yaml
  - forgejo.yaml
  - audiobookshelf.yaml
  - yopass.yaml
  - tekton.yaml
  - homelab-gitops.yaml
  - navidrome.yaml
  - bytestash.yaml
  - stirling-pdf.yaml
  - soulsync.yaml
  - vikunja.yaml
  - argocd-config.yaml
