apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tetragon-policies
  namespace: argocd
  annotations:
    argoproj.io/sync-wave: "-5"
spec:
  project: default
  source:
    repoURL: https://github.com/gwg313/homelab-gitops.git
    targetRevision: main
    path: platform/tetragon/policies
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
