apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tetragon-core
  namespace: argocd
  annotations:
    argoproj.io/sync-wave: "-10"
spec:
  project: default
  source:
    repoURL: https://github.com/gwg313/homelab-gitops.git
    targetRevision: main
    path: platform/tetragon/core
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=true

  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      namespace: ""
      jsonPointers:
        - /metadata/labels
        - /metadata/annotations
