apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yopass
  namespace: argocd
  annotations:
    argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/gwg313/homelab-gitops.git
    targetRevision: main
    path: apps/yopass
  destination:
    server: https://kubernetes.default.svc
    namespace: yopass
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
