apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 10-audit-baseline
  # - 20-enforce-execution
  # - 30-enforce-fim
  # - 40-enforce-network
  # - 50-enforce-privilege

commonLabels:
  app.kubernetes.io/part-of: tetragon-policies
