apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - tracingpolicy-shell-spawn.yaml
  - tracingpolicy-network-connections.yaml
  - tracingpolicy-sensitive-binaries.yaml
  - tracingpolicy-privilege-escalation.yaml
  - tracingpolicy-sensitive-file-access.yaml

commonLabels:
  app.kubernetes.io/part-of: tetragon-policies
