apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: detect-shell-spawn
spec:
  kprobes:
    - call: "security_bprm_check"
      syscall: false

      selectors:
        - matchBinaries:
            - operator: In
              values:
                - /bin/sh
                - /bin/bash
                - /bin/dash
                - /bin/ash
                - /busybox/sh

      args:
        - index: 0
          type: string

      return: true
