apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-harbor-redis-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: harbor-iscsi
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: harbor
    name: data-harbor-redis-0
  iscsi:
    targetPortal: truenas.local.gwg313.xyz:3260
    iqn: iqn.2005-10.org.freenas.ctl:harbor-redis
    lun: 3
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
      name: harbor-iscsi-auth
      namespace: harbor
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-harbor-trivy-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: harbor-iscsi
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: harbor
    name: data-harbor-trivy-0
  iscsi:
    targetPortal: truenas.local.gwg313.xyz:3260
    iqn: iqn.2005-10.org.freenas.ctl:harbor-trivy
    lun: 4
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
      name: harbor-iscsi-auth
      namespace: harbor
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-data-harbor-database-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: harbor-iscsi
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: harbor
    name: database-data-harbor-database-0
  iscsi:
    targetPortal: truenas.local.gwg313.xyz:3260
    iqn: iqn.2005-10.org.freenas.ctl:harbor-database
    lun: 2
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
      name: harbor-iscsi-auth
      namespace: harbor
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-jobservice
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: harbor-iscsi
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: harbor
    name: harbor-jobservice
  iscsi:
    targetPortal: truenas.local.gwg313.xyz:3260
    iqn: iqn.2005-10.org.freenas.ctl:harbor-jobservice
    lun: 0
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
      name: harbor-iscsi-auth
      namespace: harbor
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-registry
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: harbor-iscsi
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: harbor
    name: harbor-registry
  iscsi:
    targetPortal: truenas.local.gwg313.xyz:3260
    iqn: iqn.2005-10.org.freenas.ctl:harbor-registry
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
      name: harbor-iscsi-auth
      namespace: harbor
