apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-harbor-redis-0
  namespace: harbor
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: data-harbor-redis-0
  resources:
    requests:
      storage: 10Gi
  storageClassName: harbor-iscsi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-harbor-trivy-0
  namespace: harbor
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: data-harbor-trivy-0
  resources:
    requests:
      storage: 10Gi
  storageClassName: harbor-iscsi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-data-harbor-database-0
  namespace: harbor
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: database-data-harbor-database-0
  resources:
    requests:
      storage: 10Gi
  storageClassName: harbor-iscsi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-jobservice
  namespace: harbor
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: harbor-jobservice
  resources:
    requests:
      storage: 10Gi
  storageClassName: harbor-iscsi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-registry
  namespace: harbor
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: harbor-registry
  resources:
    requests:
      storage: 200Gi
  storageClassName: harbor-iscsi
