---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-admin
  namespace: harbor
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgC41SQFMF6o326C6K1PIroK6C7uH0oDTcyzBIF6P5ZUS4vL0wwtza82Qs5gU7FsKppKDB05NGyM31jfbJZIFl1C4bkYebVSaMQAS5T9dmcvfBPiJyDU4E1GBnnpy8Tjfp3mSK5jAm2sHco4A08ajSGRSbKkCYcY1GT0eSij7crADM6kC6ZG+p85qiGwg11i8laTVj1FkKOeRfUyl0n8yhG2h8QDLeFNk8m753kYqPJUipDLg1HLnmDTqWIAKo7vutPQdnyez88hNAnhL1m1klTRiqNTGOyJi3lEmBOVUBcJMHKJ9i9mD/klwbB9Ihdzey4j9q6cJiI+y2aP/fmt5+qioOT1Wyj3Kwp2UeuPFX89sDyH4ycEJEuHqbWEGZvCdj7489+R0BFKAIZxBa7b/lwZQBI1/zjwUJlIUOeB+qvDIl3XANKJWGMipUxhIISq/w0R4EA/8v/K1WlOaJIHqpLAvuRUFeWh12SNN4PKiWk9UH25SbGWq2zKDNZzaGqPeFxi75MB87I2F41LgyNoCfQ5cJ5ELwoD4VL7mbbpzxHbPCJdBAOG5Qu02yIZt3TmJnjheXCB4gltqEKzG8nqB+R19l29toGA8fbTocr9faC/UqpzP3hb/ElD59kzKDBdjgFf814OlRFiDIATYBg9bRYry9xIXGVIuuwjL3YAIaUofsGFL8ddb3T0RNWVxspfGO3Haapv44hQcAykx6N+ssg8bd0MGjgbLA7b
  template:
    metadata:
      creationTimestamp: null
      name: harbor-admin
      namespace: harbor
    type: Opaque
