apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: harbor
  namespace: harbor
spec:
  gateways:
    - istio-ingressgateway.istio-system.svc.cluster.local
  hosts:
    - harbor.local.gwg313.xyz
  http:
    - match:
        - uri:
            prefix: /api/
        - uri:
            prefix: /service/
        - uri:
            prefix: /chartrepo
        - uri:
            prefix: /c/
        - uri:
            prefix: /v1/
        - uri:
            prefix: /v2/
      route:
        - destination:
            host: harbor-core
            port:
              number: 80
    - route:
        - destination:
            host: harbor-portal
            port:
              number: 80
      timeout: 30s
