apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: audiobookshelf-cert
  namespace: istio-system
spec:
  secretName: audiobookshelf-cert
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
    - audiobooks.gwg313.xyz
