apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: audiobookshelf-iscsi
  iscsi:
    targetPortal: truenas.local.gwg313.xyz:3260
    iqn: iqn.2005-10.org.freenas.ctl:audiobookshelf-config
    lun: 0
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
      name: audiobookshelf-iscsi-auth
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-metadata-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: audiobookshelf-iscsi
  iscsi:
    targetPortal: truenas.local.gwg313.xyz:3260
    iqn: iqn.2005-10.org.freenas.ctl:audiobookshelf-metadata
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
      name: audiobookshelf-iscsi-auth
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-audiobooks-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: truenas.local.gwg313.xyz
    path: /mnt/tank/media/audiobooks
  storageClassName: audiobookshelf-nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-podcasts-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: truenas.local.gwg313.xyz
    path: /mnt/tank/media/podcasts
  storageClassName: audiobookshelf-nfs
