---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: soft-serve-pv
  namespace: soft-serve
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  nfs:
    server: truenas.local.gwg313.xyz
    path: /mnt/tank/docker-volumes/soft-serve

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: soft-serve-pvc
  namespace: soft-serve
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: soft-serve-pv
