apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - audit-process-execution.yaml
  - audit-network-connections.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "1"
