apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-ephemeral
  annotations:
    argocd.argoproj.io/sync-wave: "1"
provisioner: cluster.local/nfs-provisioner-nfs-subdir-external-provisioner
parameters:
  archiveOnDelete: "false"
  pathPattern: "ephemeral/${.PVC.namespace}/${.PVC.name}" 
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-retain
  annotations:
    argocd.argoproj.io/sync-wave: "1"
provisioner: cluster.local/nfs-provisioner-nfs-subdir-external-provisioner
parameters:
  archiveOnDelete: "false"
  pathPattern: "retained/${.PVC.namespace}/${.PVC.name}"
reclaimPolicy: Retain
volumeBindingMode: Immediate
