apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikunja-data
  namespace: vikunja
spec:
  storageClassName: nfs-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
