apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - storage.yaml
  - karakeep-secrets-sealed.yaml
  - configmap.yaml
  - network-policy.yaml
  - web-deployment.yaml
  - web-service.yaml
  - chrome-deployment.yaml
  - chrome-service.yaml
  - meilisearch-deployment.yaml
  - meilisearch-service.yaml
  - route.yaml
