apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pv.yaml
  - pvc.yaml
  - iscsi-secrets-sealed.yaml
  - navidrome-secrets-sealed.yaml
  - configmap.yaml
  - network-policy.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
