apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: navidrome
  namespace: navidrome
spec:
  parentRefs:
    - name: shared-edge-gateway
      namespace: cilium-ingress

  hostnames:
    - "music.local.gwg313.xyz"
    - "music.gwg313.xyz"
    - "music.zerotier.gwg313.xyz"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: navidrome
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-gateway-to-navidrome
  namespace: navidrome
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: cilium-ingress
  to:
    - group: ""
      kind: Service
      name: navidrome
