apiVersion: v1
kind: ConfigMap
metadata:
  name: navidrome-config
  namespace: navidrome
data:
  ND_SCANSCHEDULE: "1h"
  ND_LOGLEVEL: "info"
  ND_SESSIONTIMEOUT: "24h"
  ND_BASEURL: ""
  ND_DEVACTIVITYPANEL: "false"
