apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-data
  namespace: navidrome
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeMode: Block
  volumeName: navidrome-data-pv
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-music
  namespace: navidrome
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: navidrome-music-pv
  resources:
    requests:
      storage: 10Gi
