---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBPF+l9ludA24KQJ8BEZjAz16+X7KCjubuVkQl6WWmRR5DdcNYjePcrtG++7wVbuamEDdsE1iZ+hGyHjSCpxt843Z+CqUZSSPRtpj71E1Gf6jsHr1+cQ34pWR8WZnJUyMJeaP3qgFxvX+05KGab3ejTt0hC3NB7T2UnfTUMwQaLgk8qf4wjsSkQhUtvcMwnYZ5HJlXGq/Nk4V45ytL6syWcpgMJ+ZN6ZkrGKkAN5NcbRwCeK8ugfoSHjBB/qu+gz5/UoDOtqa7dY0hr8fbhvuBPefNj2vIffca7H8ZqNmlsfLKBNgc1N6JHkFHFWCwAy6rm7mznw4gMvi031KHcvMalS2WXaomSBRlPILnA4IAqIaOf568u9xpYhJYCGosYwIPZBp+bI4QS63NVSgThrN2SR1lZpC6XoritSvvjI8v0/GHW+BDXDS6M6XVjU6W0eX04JpizAnoQtwoJpM99r4Yk5zvE9Ipl5MEamcTGOgUN8MXg2SwAtCJl9WB7RwMMM0LpkZHgQc62XNxyaf7Me2ZNLtLN+n4B8nRTXkv3I4crskoJiIXNp0FWktg6nHOMha0tdJUD5R/y4CgbtqhY2mEtBI7ztNuvXwwUVRPr6F9mL0dWyv+k7E2UC279OINC4k8as+8i2wq1ZSkSb9aKHfe5mAScUs7qOC1XRGWOi2pYhIHNBgNA3KCWFib7ouDCujl1aEpjqqs3tMkY0jlCJZpJEcsW4BerDZXvmvuyLqQhgTQi3CqV4alF
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
