apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo
  labels:
    app: forgejo
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: forgejo
  template:
    metadata:
      labels:
        app: forgejo
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: forgejo
          image: codeberg.org/forgejo/forgejo:11-rootless

          ports:
            - containerPort: 3000
            - containerPort: 2222
          env:
            - name: FORGEJO__server__ROOT_URL
              value: "https://git.gwg313.xyz/"
            - name: FORGEJO__ssh__START_SSH_SERVER
              value: "false"
            # - name: FORGEJO__ssh__PORT
            #   value: "2222"
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: forgejo-pvc
