---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: quay-config-bundle
  namespace: quay-enterprise
spec:
  encryptedData:
    config.yaml: AgB9d8bDZB/+b61fvGW/KF0miNjU3HNDSkcLp/6vsDMKGdzyaPx9ckBOhCgaYb6HSvNjG828OixpUrHUiymVuji/MaQMQ01kUfidmD0C7KHXuw7SSHP15/CoGHRwG271LNIA12wKtHKPuzAOCoxTDncpG3VWraFdjIO54l08lZDAvbESy0kB4er9zE+ne4C1U8oatf+MqAyBUe4vGKCOqRe0DAUZQijlXNI3U/5NlmxhyqYpmiQcYhTuaJ3z5pbjc9tNpQckAWCqNMNfCM3dQDef1k8qMal/QcxXEX+5B5J+3PgswwNj2Nu3O57mmHgOmAG79eur0OSDVnHlo/UUMqWkPmWQ6sO9K/D+Mg1EAp2Epv5TxIod8zFesjP9o+eiLNSPjpX/7jWVg0TkflvJPqG3rtdwU9QfC/4OkDujmkcDlr0J7BzdV4HKfEWP9q07MwMx+Z0wPpKHCqPOidlDW6xfnghu2iiXvF1CWLnHBli1/lzHT4RynBkEtD6tMtJkAahOQL/ubS8HVjIz2h3uRHb0J8TgUiFj0Z1jqEh7GVj43HpUBMjaDXdSV6277xBCIuU2E4Arti/6G7WU38ry/nSf+gckKAsoMBqQtWnGtbezM1FrURLbfHpVwxUq1MngFV+enDMJYjb2D5hjsFfdFfEqt2QfEJhNx9U38L/E9O0J+jFounDoKg6/r83kHbAQRprZKq8k1DEw2bXbUbT2OYogVjHmQDYEs1KV1u4HDuTYJD5qGoNrU+i4FlLR98WhnDbmxoYMtAVEVCS3JDvODTIXMXiDlXHATWpXl8tYnOmpgR+PVGWQBrL0kGrKHW9Fk/l58IOlcJk3PpHnx07J4ehpnX6LdZVGkMDp/P8uSrpn8F+UOlwcKKnAmp6ckOH8wQ3c2L7SlhuhgHtnGockACZ3bwsZWSURnb3mdQWEHe/dGmVFib6WzKHnFRZvW4KzdEBUF+cyP4QMPwhsWblRFVv0To1RJVyP+MDSIfsWfboicWXad7ovADnUQXCsbI+OpGRdeC9kpJHmc0XeGS9GdZZWRuugdA4z9uwIVkW5nI9v4FVI+g==
  template:
    metadata:
      creationTimestamp: null
      name: quay-config-bundle
      namespace: quay-enterprise
    type: Opaque
