apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-tag
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: validate-image-tag
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              selector:
                matchExpressions:
                  - key: app.kubernetes.io/managed-by
                    operator: In
                    values:
                      - tekton-pipelines
                  - key: tekton.dev/task
                    operator: Exists
          - resources:
              namespaceSelector:
                matchLabels:
                  policy.home.arpa/allow-latest-tag: "true"
      validate:
        message: "Using the 'latest' tag or omitting image tags is forbidden. Use a specific version semantic tag."
        foreach:
          - list: "request.object.spec.containers"
            deny:
              conditions:
                any:
                  - key: "{{ regex_match('^.*:latest$', '{{ element.image }}') }}"
                    operator: Equals
                    value: true
                  - key: "{{ !contains('{{ element.image }}', ':') }}"
                    operator: Equals
                    value: true
