apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: woodpecker-cert
  namespace: istio-system
spec:
  secretName: woodpecker-cert
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
    - ci.gwg313.xyz
