apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: woodpecker-shared-storage
  namespace: woodpecker
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-client
