apiVersion: v1
kind: PersistentVolume
metadata:
  name: woodpecker-agent-pv5
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  iscsi:
    targetPortal: truenas.local.gwg313.xyz
    iqn: iqn.2005-10.org.freenas.ctl:woodpecker-agent
    lun: 1
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
      name: woodpecker-iscsi-auth
      namespace: woodpecker
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: woodpecker-agent-pvc5
  namespace: woodpecker
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: woodpecker-agent-pv5
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: woodpecker-server-pv5
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  iscsi:
    targetPortal: truenas.local.gwg313.xyz
    iqn: iqn.2005-10.org.freenas.ctl:woodpecker-server
    lun: 0
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
      name: woodpecker-iscsi-auth
      namespace: woodpecker
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: woodpecker-server-pvc5
  namespace: woodpecker
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: woodpecker-server-pv5
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-woodpecker-server-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    targetPortal: truenas.local.gwg313.xyz
    iqn: iqn.2005-10.org.freenas.ctl:woodpecker-data
    lun: 2
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
      name: woodpecker-iscsi-auth
      namespace: woodpecker
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-woodpecker-server-0
  namespace: woodpecker
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  volumeName: data-woodpecker-server-0
  storageClassName: "" # must match PV
