apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tuwunel-data
  namespace: tuwunel
spec:
  storageClassName: nfs-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
