---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tuwunel-secrets
  namespace: tuwunel
spec:
  encryptedData:
    TUWUNEL_REGISTRATION_TOKEN: AgBKQp17rNoKjFDPmV0u0uVP5CVDJmkr9eji3Nc6t/nnrJjXhpc1QhmBhZ3tQSpvU8wQvp4ZaDCIEVoloZmwAB1YyDoErsxLnGB9laqnxTMXIqZoWVYPqe88UvXTusqWQ1km8fOJDIp+U5BLMRz6+LMLLru7S08lJT6hXT9PhdfITg7ccE4M3C7UbX1675JLpQLOxeDyGZv038qB7y+ms6CAgOacSSWEEk2DH0P+zrvlp3Rn+0vd+b1FcbLI+npNqD8mbMY580YNYk0Q3PzDCurRP7DtF7C4CWOiyCt+qoCWEDC58e3wc9onztwDPCVN9YceZIkmKmSfVOpamHoAltbSfr9B7qisZHQ6oqboGwni9ShvPJ23zWCHvZwtuVnyQKPUTZHja13ldWlivAZHxazYkhRKuXewiYRMWAXzHoshkeyMI8IHzZ+uh5lB7oHPZPg4r60lrcySdWaiEn99CD+RCNve3tVhPzH+h9sbe5AYr3KAPzo9S7cczYhvpuBH6iauxv+3NXoII7G7MHN/CNTdWZPVoSlCrqONuu24/WMyjYooWv+uJEY40gSEeFFFgKw0Mfts67w4xNmBzZX9gCAH1IC1r5a7iXxhN361MNip3kgfRHLPaklr3+Ks6MPAFiV6p6y2lhgaBm0m6WFvG3UrfjJ97xQt+/VdEdYkmFL6c50C0uH0Wd8w4KXK3kuP56wDRblZcrNmuzCZXma7FT7ZJSPy3wDO75Q=
  template:
    metadata:
      name: tuwunel-secrets
      namespace: tuwunel
    type: Opaque
