apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkwarden
  namespace: linkwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkwarden
  template:
    metadata:
      labels:
        app: linkwarden
    spec:
      containers:
        - name: linkwarden
          image: ghcr.io/linkwarden/linkwarden:latest
          ports:
            - containerPort: 3000
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret-linkwarden
                  key: POSTGRESQL_PASSWORD
            - name: DATABASE_URL
              value: "postgres://postgres:$(POSTGRES_PASSWORD)@postgres:5432/postgres"
            - name: NEXTAUTH_SECRET
              value: SgG4jVtm9ukRKEbJw7vw
            - name: NEXTAUTH_URL
              value: "https://bookmarks.gwg313.xyz/api/v1/auth"
            - name: NEXT_PUBLIC_DISABLE_REGISTRATION
              value: "true"
          volumeMounts:
            - mountPath: /data/data
              name: linkwarden-data
      volumes:
        - name: linkwarden-data
          persistentVolumeClaim:
            claimName: linkwarden-data-pvc
