apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkwarden-postgres-pvc
  namespace: linkwarden
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
  volumeName: linkwarden-postgres-pv
