---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  encryptedData:
    api-token: AgBHIRGTABWJsIbiEPN/Vaaj7AaEs9VRD40coTXBInHsKg2lXp6NmVBZWsnqSEI4GkgWTWobjAaDXTfahftG7ITxrxBHvCVhmwolIf6MbxQ8saH0zH4oOIRH4SfOIGnuY+7dwaKS+G+Bv8BUVBTsYuU2+F8nAiSMrWIBSJqk9tJXJO6doiIfWZOHsASyMoJfkhH0u/c0ELmhXG6ymOVfHHw3oBXMWFuR5bRptbGLxUeSXPUtR7X5trhKb7+0CPJ2Qmlmh2gf0ioxeKNW4SexkBKGzqFRiUPHAsWPr6nC6Lj8zKOY4X3XlguuA6jx1PUAG8ffChoXcCcjDutf/XBBG+gheFvOP4T9mO80LXjJHADI2U9fB4bXgnVbW824cmAXlvrIjWfvTWoaI2A9wfPwcZbbB4/5KAg/4CGBic3+hcX9SSOVNkiOXfQGm9Q/X7s3Z/v6hHLNIDd7sRXrR0t16nad2HnVr2VDPUTdEL1hNgR6RBVzopXudye1tsa0ECqfHgoUlpYkGya2UyBZpZBCZAar8v2MUi2rkk+cBGuBfu5dVd/KsTePWqDu9tqe3t6RtzA7ygHZqUPhOtAtRrrnRKMyQmqjwZ8fzz9TeXswmn7qwreZDSVXW1ZG8kIhd6CeCTt0l+uNiUSmQ0EbJ9vnpqnAWsCU10cwgBRO97JxOkf7A3YWSZszgwVpyiND7cKFsDS3M4ZNRTtyooLIH4WgBKPiUEC5LT6fFzOELPAJ2VEv4KMtX7HQ5jQh
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
