# Enable Istio base + control plane + ingress gateway
global:
  istioNamespace: istio-system

istiod:
  enabled: true
  meshConfig:
    enablePrometheusMerge: true
    accessLogFile: /dev/stdout
  pilot:
    autoscaleEnabled: false

gateway:
  enabled: true
  name: istio-ingressgateway
  service:
    type: LoadBalancer
