---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bytestash-secret
  namespace: bytestash
spec:
  encryptedData:
    JWT_SECRET_KEY: AgBCDeFnaNdujQUOyy739IPIZ0lnZ5YMHZiHxiU+czvIWVkRRPqdrcmUc9+zrA7Hxmg4CxVqpONQ17eehepc8MWmz7M7cug0NMH55g3tJGp0cQf7SO2tcZjGggEu232E3MkLP8O/PSxRxcGGCtVAwaNx7b4Ay390MkgivSJIKuC8EdJeitFiX+MKHnmR81nlvjo0QhuE64Rsbq1NkvJtCYQhq3aUIn9aFWkKPM7Iz3CB4j44C4VVwB7DgROw+hVFUGdptdBuM9aoWPLF/LiGv9V+GnH8EQuInmr7XwrL2Fqw28iw35Q9W6gtcOSGnkSF1EwlU7z7fuoRqosqYq2zRiuYHxuCqqjIC2CyWn/VEpG/SAa2V0NcD4jPRrLcgYjX6NPfFt4Q5b+FkTzsWkp5Wu2UwYUjg+X7WqOoBt0rJsDRywOEVsPAPspFT3E6lnxuZMpeSZ0Y0czbKQxzQz/OTDaGq1letPnuqTIz0rj5133bevPYyGqyMA+JyVnG+gjthPXfGBAEJtS/uGDDW7j0b37EG6SZdNnZEMTpY+aYjg9cc1d1PLiIqQwmhFb4D1Exf5SKj/+1Ouged+eZQxsWaGg1gZ9iVSiofjx7pvopXpSDBtfpE9Va+PLbukCQs4qhlNutJ6qfZmdpZKsJR2iBc/lcxCxJNbz29vWYOjhRtQUcvusve2ZWC5dB7uQnml2jZ1tBEvuIAvHnN1r6DhjX1RkduUpNwFNbuYXvSyga
  template:
    metadata:
      creationTimestamp: null
      name: bytestash-secret
      namespace: bytestash
