apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bytestash-cert
  namespace: istio-system
spec:
  secretName: bytestash-cert
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
    - snippets.gwg313.xyz
