---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homebox-secrets
  namespace: homebox
spec:
  encryptedData:
    HBOX_AUTH_API_KEY_PEPPER: AgCVukM6JoQf13x56W16HkWv3wTW8TXY73eMTjFS1CSJ4BBFVet1qMX+VD5PtFLhcUf9tNW+u/9PMtiQs7ZuOuitV+K6l1WBN1Xi1Khr9td8lSVQVWnSsq1UTqCtsiA+Jx5P/3OjXMtIq3IeZZYnJmIpGck1mtLrd2sIFAE5agACoBjqhzQOfPUp6vZG9JmT0uDEHK3IgcUzweJPJF7d6XwcyfEcF2SGnlMsswaNag+Iu9m4Yv3yX1a0Xke3+jFgppmvICozdgMWj+6kY9e7RjEWxXM0VYzeQzEc+vMquHtvFs6uoA1kBc3OatJRMBnkBM8zzvYb7TMjCIPgg9EEF2po5MylzlGinYWfA2XN1J1DJ3vlY6dI6p3RMsE0fwP2V8at2/s6slLcdrXsodEZXLQFeJSn+BywCKuqtBh/O+cmvLSsfN2p4OJC6TJ0O1i/G8L8P4AhIBItFDI5nxmu69ovFgLVddy1yXtZsvOjsAbbf6MUDnHv42bJtVE0CjTYD5vQYqNqPRqKmNiystHZxkJIU8hyB4aiwl3RhSVzmt5inPPnjyUdyvFDmA4n7S/QerwepvqC8tc/DcPgrkak7VjlfcaZS73FMnEm7CONUwnEHo4HgvWUrvq8wci4pcvERGgZ61noJruVfMpZjLVSm3TBCB2V9YbJ7kne6BurW8HrHtLlpNoBaEs4k3szeNdlV/uImZUFFuQRFw2c/g9VLKpfURwf13G0VhJmMxwmIQNfxe+VZuyiXdqPWS9OIZDfxjaaUJ/DcPl0tMGxDnSI+ZZ/
  template:
    metadata:
      name: homebox-secrets
      namespace: homebox
    type: Opaque
