apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stirling-custom-files
  namespace: stirling-pdf
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
  storageClassName: nfs-client
