apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stirling-training-data
  namespace: stirling-pdf
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
