apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bytestash
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gwg313/homelab-gitops
    targetRevision: main
    path: bytestash
  destination:
    server: https://kubernetes.default.svc
    namespace: bytestash
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
