apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quay
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: quay-enterprise
  source:
    repoURL: https://github.com/utkuozdemir/quay-standalone-helm-chart.git
    targetRevision: main
    path: chart
    helm:
      releaseName: quay
      values: |
        enabledComponents:
          - quay
          - postgres
          - redis

        quay:
          image:
            repository: quay.io/projectquay/quay
            tag: latest
          configBundleSecret: quay-config-bundle
          ingress:
            enabled: false
          service:
            type: ClusterIP
          persistentVolumeClaim:
            existingClaim: quay-quay-config-storage

        postgres:
          persistence:
            existingClaim: quay-postgres
          user: quayuser
          password: quaypass
          database: quay
          service:
            type: ClusterIP

        redis:
          persistence:
            enabled: true
            existingClaim: quay-redis
          service:
            type: ClusterIP
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
