apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: woodpecker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://woodpecker-ci.org/
    chart: woodpecker
    targetRevision: 3.2.0
    helm:
      releaseName: woodpecker
      values: |
        server:
          env:
            WOODPECKER_HOST: "https://ci.gwg313.xyz"
            WOODPECKER_PLUGINS_PRIVILEGED: "plugins/docker"
          extraSecretNamesForEnvFrom:
            - woodpecker-server-secrets
          persistentVolume:
            enabled: true
            existingClaim: woodpecker-server-pvc5

        agent:
          enabled: true
          replicaCount: 1
          extraSecretNamesForEnvFrom:
            - woodpecker-agent-secrets
          env:
            WOODPECKER_SERVER: "woodpecker-server:9000"
          persistence:
            enabled: true
            existingClaim: woodpecker-agent-pvc5
          securityContext:
            privileged: true    
  destination:
    server: https://kubernetes.default.svc
    namespace: woodpecker
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
