apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: woodpecker-manifests
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gwg313/homelab-gitops
    targetRevision: HEAD
    path: woodpecker
  destination:
    server: https://kubernetes.default.svc
    namespace: woodpecker
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
