apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-cert
  namespace: istio-system
spec:
  secretName: minio-cert
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
    - s3.gwg313.xyz
    - s3-console.gwg313.xyz
