apiVersion: v1
kind: PersistentVolume
metadata:
  name: karakeep-data-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    targetPortal: truenas.local.gwg313.xyz:3260
    iqn: iqn.2005-10.org.freenas.ctl:karakeep-data
    lun: 0
    fsType: ext4
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
      name: karakeep-iscsi-auth
  claimRef:
    namespace: karakeep
    name: karakeep-data-pvc
