apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: karakeep-meilisearch-pvc
  namespace: karakeep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
  volumeName: karakeep-meilisearch-pv
