---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: plane-app-keys
  namespace: plane
spec:
  encryptedData:
    LIVE_SERVER_SECRET_KEY: AgAvX2eGDz9ZdyJdS1HIpVNEvd114JIEkqMyGIujnxl+9Zf5Qyp1Ok53crInVQ+U+5TAHdYDLfsjI+xLkOnd3UnkN9Z8DfjFMziN/UBFOdDbSR0BvN9ufyw9DHFENbgA70qKShOc+rRvkjgm4yn1WtsELExgD45IyZxOO/kIc/+2AXiaGzGcYuf9pBNRN8nI7DZajlav3g/Zc78f0XVKMB1sq/UyW7B0yqAISxW27LyLv2TkDetmLxrVEhESj7/bJ/luPLH76bKMmiP7VVAV5rIB8HNcXgYlGDgR+ss2SZDOaxKF1RHqQG8upuQUqvt/6Vp8Is2SBJQLQoS7y/n16+m6XROGksWlfYUl6Bb1pSU0kkGaHIGmknVLUhBMAnap8Ox1xceIcGTeNc1S6jvJnKJwfJcaVvPfaRQOWNTsSsBd/2D1JkaA6R24Mg2Tgv9D/wEFLgEjyWBxqcLZwB+vJxn7cjkDfy4/W8RuWjzMJJ+77NPbEVVxhBRBiYlJu9PzElkUSucZ7q+/7fijalNbZdzC2vCvTjmoLQ836UF+SzzSqUxrYOfv+dutbqNZ+m30qadGCOBDGZe0D82fF/j4P8rXRXqGyo1CI0XgDiFY373O8Wc/MG6AUsXR44pL+e1xImEJJUDj5fmFN9d6wd+1/QtrNmjBh+2Vhhy8/74HBubZZdpxK/PO5p9sRQxW9f95jrpgJltOxeNYCW5qLem/i7k4lx0cyCDsUhaMqkWH4G1U9HkiQgH8YUY0AK044TtxRE98+ibQvkcuyHS7imxFA6Fl
    SECRET_KEY: AgB5wDyfDu6EyHSJWDqmufrXRG0XjtqPlrDWqggIHzoGWsUuXQeE8mqLX85UUlQyq/lo42M2GMEtHsf1pzRBj+Sh1ZyQIAu15msJRwtRyoyClPIBNWUErXVeI34GAS8UxMnb6w8+ZJ/tEWmvu//y3JKh0a+U4Ob+TtWCXA7ZVt614Id9y5YnJmHal82My9mrSQ94GHLwCnWWAWlRoAAVFzlutW37O10hr/K+kwdloh5GiRDvXbFmY61otohefn/bNZS3ZtzY2N9yj2SsKmy25ubdfYJ7PX51C3uIh96bKrb7XWabqWU+pn4KYEcmGh33AmDPgkLOp4cXhpeD+jGp/m34td347VX1eZbPGfDLyYrA/omcLbbPa5m9TXKbU3L4ptaJCGM/XsEtAsbXNS5Azc1HFzz0z7fh8V/lRCl3f+EZKlvkusdArL/CoD9KYdn77KqCsh/CkAn8RWGl/d01VC7lAWDOtYYeyZ035IYeBIn4cTLdafZ/4xV1g1oJVQRSIC+Vh8+0bJB/sPxpPAvT8JHnjhdcf21czpkIYaI0KbqL1N4bg34NxvhK7RA8995t/fMt9a8OHT6sMho2Htk6D9fCLipgfTZBvK0/uMytbqe+gIz2jI6Ng1dq+Sn5ltg1700W6DYYp/LJYlnZXQuassTHhn+X4TclfWDvYiIfuYKd9qpcW4SawGnq1zy95iBTU2qZ/p6aqlo4YsQcIQT+2/w6CNsR3+MjyiaCGvP1mOcbdh/DnE4SN1cibefhZQgS7ns8tSdyaCyx1bePLMZjyL3Y
  template:
    metadata:
      name: plane-app-keys
      namespace: plane
    type: Opaque
