apiVersion: v2
name: plane
description: Plane project management
type: application
version: 1.0.0
appVersion: 1.4.1

dependencies:
  - name: plane-ce
    version: 1.8.0
    repository: https://helm.plane.so/
