---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kube-prometheus-stack-grafana
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  encryptedData:
    admin-password: AgCdmekbfg75MUC/4us+SE5QQrnqeBRQjUKzlnINYQo9Z4zw5TO+x4MpFR8Jsf48ZcP4xbOldZfWNf4Y5hv2SVxonuluEDtKH1z38n/Jz4BRRUNkJkfQPmzShwkCvu2QbtVdQEqIxDW6ekksrD+Nk0IRoV1dNEr2ajNcZjzfrbBM4AvcpNkVg0vy4lH2HP+ckecdJ59gRrrUZ4ysgSJKRsz9fYtBtfuYMVVmtyCai/QHaeXYXhoX2VKuxf5G6HSGqbY7dTOy9MoEHIjnxF8v+GMieBoHpLo+uhuSOP8cZ+0oBSAbr3MVfA1QSz2DIsewnVFa+x0xFgtlltVrpLoW6AkQu71je/9tzfc1OKfftsBCYUWaMfFpnx/jFgUla1ntkiqmQaL1yGmA8QbTa9LGjAbADsWFTp3FOjExWYDfQ1VMLukHolNau+aSvf31PgNbovX/e+WlMfGk2RNN41EAFc1q1s20hO/mrMq42WJ38HBs93iQgFSKGiw551x6eIzK4uIqD/8ghMjKCGUmDgUxibrwR4nbeprLU0wviASN5ABHYiNwzhpZlupe/VAKiwiGCAY9Ni8wUfwF/GUyujnh88UvgvIW2KY5bJOLMPx2QnfVLZlUH8d/Fzy4RwHPLt1vi6mYSOYdDf/USNlXTIO2AZAQJFVkFQxW/7Hgb2u6M9h2tHRejXkFmoWFK7B5+xOGiQ7SxevRC9TiqBHQzk0kbXSviPWvHmMXMDVi
    admin-user: AgABVgocIJ0WxsJ2qB3twb0sLpA2yoOsOYSNVtKqokGIeamDQqhAltOJcUH9H4PgHqG/miK55AaV/XOoM56Nnj0Any5LOSQv829IIvpgJCWF3jplU1nL74kDt/crh3i/c2i9NReUubPrE+B2Bgzb751CxOrjAG4vvo2dJYQNE3ZmgRHSNrRuHrWDejDLVWnZMkCLBw3CfEXqaw5AvU1Gb0z2/UHu5j19XzBX9kDPhnMCKATEdAbi0x/S+eWh4jbyDs60IrfzovtJQsw9IrVKcFz+BxlHVQPdRw8H3cZ10Imu/c6Y5dKFdyX+pK+A8nlvH9oCgpH02D5ITJDK1GkPq2zEE6J4wVbcR9vFqUwAEZlwWI/H6J11jdoGFcxEFc5XcJfouAcrdrKH1j82wd5SUJMLdZN8MQ+ATNZfPjji0fyxAuZKi/Bs24QlGQg3R6iOIFHHE47HuyksWiGR171hQ0NBTKkDGQfMvKV5K65IgFumGw9f2weWrOzkWQoUljDkqDv7cF0f9iNAuZPjrYapk8/ebKugvobnHoKgY1eLm3/A3NCuWjjPwiark2tpaMsfeVxLLKgzRVLxQm4C8hPnvkjV7E+F17p483/s+NlHSFkLQh5o9Su+mbuAJJQutrDa4zlI0d42t3sDnwCOOfgwweMcqdViqmmhuMNbGY1SRWicmBdmZOokBeGCdUl5ZOi6aEtaoXJzp2k=
  template:
    metadata:
      creationTimestamp: null
      name: kube-prometheus-stack-grafana
      namespace: monitoring
    type: Opaque
